"""
BBCode templates for RED upload descriptions.

Defines template strings used by the description generator. Templates
use Python str.format() placeholders for substitution.

Templates are organized as named constants that can be overridden
or extended. Each template represents a section of the final output.
"""

from __future__ import annotations


# ---- Section templates (used by sections.py) ----

HEADER_TEMPLATE = (
    "[b][size=4]Release Information[/size][/b]\n"
    "[hr]"
)

FORMAT_SECTION = (
    "[b]Format:[/b] {format}\n"
    "[b]Bitrate:[/b] {bitrate}\n"
    "[b]Source:[/b] {source}\n"
)

BIT_DEPTH_LINE = "[b]Bit Depth:[/b] {bit_depth}bit\n"

SAMPLE_RATE_LINE = "[b]Sample Rate:[/b] {sample_rate}Hz\n"

TOOLS_SECTION = (
    "\n[b][size=3]Tools Used[/size][/b]\n"
    "[hr]\n"
    "{tools_list}\n"
)

LOG_SECTION = (
    "\n[b][size=3]Log Analysis[/size][/b]\n"
    "[hr]\n"
    "[b]Log Type:[/b] {log_type}\n"
    "[b]Log Score:[/b] {log_score}/100\n"
    "[b]Confidence:[/b] {confidence}\n"
)

LOG_ISSUES_HEADER = "\n[b]Issues Found:[/b]\n"
LOG_ISSUE_LINE = "[color=red]• {issue}[/color]\n"
LOG_NO_ISSUES = "[color=green]• No issues detected[/color]\n"

SPECTROGRAM_SECTION = (
    "\n[b][size=3]Spectrogram[/size][/b]\n"
    "[hr]\n"
    "[img]{spectrogram_url}[/img]\n"
)

DYNAMIC_RANGE_SECTION = (
    "\n[b][size=3]Dynamic Range[/size][/b]\n"
    "[hr]\n"
    "[b]DR Value:[/b] {dr_value}\n"
)

RISK_SECTION_SAFE = (
    "\n[b][size=3]Quality Assessment[/size][/b]\n"
    "[hr]\n"
    "[color=green][b]✅ Risk Level: {level}[/b][/color]\n"
    "[b]Score:[/b] {score}/100\n"
)

RISK_SECTION_WARNING = (
    "\n[b][size=3]⚠️ Quality Assessment[/size][/b]\n"
    "[hr]\n"
    "[color=orange][b]⚠️ Risk Level: {level}[/b][/color]\n"
    "[b]Score:[/b] {score}/100\n"
)

RISK_SECTION_DANGER = (
    "\n[b][size=3]🚨 Quality Assessment[/size][/b]\n"
    "[hr]\n"
    "[color=red][b]🚨 Risk Level: {level}[/b][/color]\n"
    "[b]Score:[/b] {score}/100\n"
)

RISK_REASON_LINE = "[color=red]• {reason}[/color]\n"
RISK_SUGGESTION_LINE = "[color=orange]→ {suggestion}[/color]\n"

FOOTER_TEMPLATE = (
    "\n[hr]\n"
    "[size=1][color=gray]Generated by RedactedAudioToolbox Quality Audit System v1.0[/color][/size]\n"
)

# ---- Full description template (assembled from sections) ----

DEFAULT_FULL_TEMPLATE = (
    "{header}"
    "{format_section}"
    "{tools_section}"
    "{log_section}"
    "{spectrogram_section}"
    "{dr_section}"
    "{risk_section}"
    "{footer}"
)
